version: "3.7"

services:
  aermetic:
    container_name: aermetric
    restart: always
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    command: run
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    env_file:
      .env
    ports:
      - 127.0.0.1:8005:8000
    links:
      - db
    depends_on:
      - db


  db:
    container_name: aermetric_db
    restart: always
    image: postgres:12.4-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      .env
    ports:
      - 5435:5432

volumes:
  postgres-data: