# Generated by Django 3.2.9 on 2022-06-04 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Airplane')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PRE_LEGEND', 'PreLegend'), ('REPEAT_LEGEND', 'Repeat Legend'), ('LEGEND', 'Legend'), ('UPPER_A', 'Upper A'), ('PAIRED_B', 'Paired B'), ('PAIRED_A', 'Paired A'), ('LOWER_A', 'Lower A'), ('LOWER_B', 'Lower B'), ('WARNING', 'Warning')], db_index=True, max_length=15)),
                ('priority', models.PositiveSmallIntegerField(choices=[(0, 'Easy'), (1, 'Usual'), (2, 'Hard')], db_index=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Started'), (1, 'In progress'), (3, 'Kickback'), (2, 'Suspend'), (4, 'Finished')], db_index=True)),
                ('info_count', models.IntegerField()),
                ('errors_count', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aircraft', to='service.aircraft')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['type'],
            },
        ),
    ]
